# Generated by Django 4.2.5 on 2023-09-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeesApp', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='hire_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(choices=[('TR', 'Trainee'), ('JR', 'Junior'), ('MD', 'Middle'), ('SR', 'Senior'), ('LD', 'Lead')], default='TR', max_length=2),
        ),
    ]
